name = "kks-res-web"
compatibility_date = "2025-04-15"
main = "./.output/server/index.mjs"

[build]
command = "npm ci --legacy-peer-deps --no-optional && npm run generate"
dist = ".output/public"
node_compat = true

[build.environment]
NODE_VERSION = "23"
NODE_OPTIONS = "--max-old-space-size=4096"

[env.production]
vars = { NUXT_ZF_API_HOST = "https://mn.iqianba.cn/kksWeb", NUXT_WX_STATE = "iqianba" }

[site]
bucket = ".output/public"

[site.static]
exclude = [
  "**/*.js.map",
  "**/*.css.map",
  "_nuxt/_redirects",
  "_nuxt/_headers"
]
